version: '3.8'

services:
  go:
    image: ramdas1999/myapp-go:latest
    container_name: go_app
    ports:
      - "8080:8080"

  nextjs:
    image: ramdas1999/myapp-nextjs:latest
    container_name: nextjs_app
    ports:
      - "3000:3000"

  wordpress:
    image: ramdas1999/myapp-wordpress:latest
    container_name: wordpress_app
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ramdas
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: ramdas
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
