name: WordPress CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPCS
      run: vendor/bin/phpcs --standard=WordPress wp-content

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add necessary steps to build and push the WordPress application Docker image

      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@v2.1.2
        with:
          server_ip: ${{ secrets.STAGING_SERVER_IP }}
          server_port: ${{ secrets.STAGING_SERVER_PORT }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          password: ${{ secrets.STAGING_SERVER_PASSWORD }}
          local_path: ./wordpress
          remote_path: /var/www/wordpress    
