name: Go CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod download

    - name: Lint
      run: |
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
        golangci-lint run --config .golangci.yml

    - name: Test
      run: go test -v ./...
    

      
