name: Go CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod download

    - name: Lint
      run: |
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
        golangci-lint run --config .golangci.yml

    - name: Test
      run: go test -v ./...
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add necessary steps to build and push the Go application Docker image

      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@v2.1.2
        with:
          server_ip: ${{ secrets.STAGING_SERVER_IP }}
          server_port: ${{ secrets.STAGING_SERVER_PORT }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          password: ${{ secrets.STAGING_SERVER_PASSWORD }}
          local_path: ./go
          remote_path: /var/www/go    

      
